---
title: "FUMS"
subtitle: "**F**resh-**U**p your **M**ath **S**kills"
---

```{r setup, include=FALSE}
# ---------------------------------------------------------------------------
# Einige Funktionen und Variabeln sind in die Datei 'prelude.R' ausgelagert.
# Diese werden hier nachgeladen und angepasst.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
source("prelude.R")
initPrelude()

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Sichert zu, dass die entsprechenden Daten auch vorhanden sind. 
# Ggf. werden sie von dem übergebenden Link geladen und lokal gespeichert.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# tips <- assertData("tips.csv", "https://goo.gl/whKjnl")

library(knitr)
options(knitr.graphics.error = FALSE)

# ---------------------------------------------------------------------------
```
```{r localKnitrButtonSetup, eval=!RENDEREDBYSCRIPT, echo=FALSE, include=FALSE}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Einstellungen für den Fall, dass man den knitr-Button nutzt. Sonst bitte
# 'eval=FALSE' einstellen!
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

privateVorstellung <<- FALSE   # Zeige die Private Vorstellung
UseCache <<- FALSE


if (!exists("prelude.rendertools")) {
    loadPrelude("prelude_rendertools.R")
}

createPrivateYaml("Dozent*in", "WiSe 2020/21", "Studienort")
createPrivateYaml("Dipl.-Math. Norman Markgraf", "WiSe 2020/21", "Düsseldorf/Münster/Gütersloh")

# Erzeuge Skript "DozentenSkript", "StudierendenSkript" oder "LösungsSkript": 
makeSkriptOfType("DozentenSkript") 
```

```{r setUpChildren, eval=TRUE, include=FALSE}
childrenToInclude <- c(
    "Einleitung",
    "AufbauZahlen",
    "Bruchrechnung",
    "BinomischeFormeln",
    "Potenzgesetze",
    "Logarithmen",
    "QuadratischeGleichungen",
    "Funktionen",
    "Ungleichungen",
    "Summenzeichen",
    "Produktzeichen",
    "Epilog"
)
if (FALSE) { # Zum debuggen auf TRUE setzen!
  childrenToInclude <- c("Kind-Vorlage")
}
includeChild <- function(name, children=childrenToInclude, all=FALSE) {
    ifelse(all, TRUE, (name %in% children))
}
```


```{r child = './Inhalte/Einleitung.Rmd', eval=includeChild("Einleitung")}
```

```{r child = './private/private-Vorstellung.Rmd', eval = privateVorstellung}
```

```{r child = './Inhalte/AufbauZahlen.Rmd', eval = includeChild("AufbauZahlen")}
```

```{r child = './Inhalte/Bruchrechnung.Rmd', eval = includeChild("Bruchrechnung")}
```

```{r child = './Inhalte/BinomischeFormeln.Rmd', eval = includeChild("BinomischeFormeln")}
```

```{r child = './Inhalte/Potenzgesetze.Rmd', eval = includeChild("Potenzgesetze")}
```

```{r child = './Inhalte/Logarithmen.Rmd', eval = includeChild("Logarithmen")}
```

```{r child = './Inhalte/QuadratischeGleichungen.Rmd', eval = includeChild("QuadratischeGleichungen")}
```

```{r child = './Inhalte/Funktionen.Rmd', eval = includeChild("Funktionen")}
```

```{r child = './Inhalte/Ungleichungen.Rmd', eval = includeChild("Ungleichungen")}
```

```{r child = './Inhalte/Summenzeichen.Rmd', eval = includeChild("Summenzeichen")}
```

```{r child = './Inhalte/Produktzeichen.Rmd', eval = includeChild("Produktzeichen")}
```

```{r child = './Inhalte/Epilog.Rmd', eval = includeChild("Epilog")}
```

```{r finalize, include=FALSE}
# ---------------------------------------------------------------------------
# Setzt einige Parameter zurück.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
finalizePrelude()
```
